theme: jekyll-theme-minimal

title: Learn Coding
description: "A comprehensive, open-source educational resource for Web Development, Systems Programming, Databases, and Version Control."
baseurl: "/coding"
url: "https://latikeshh.github.io"

# GitHub Pages settings & plugins
plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-feed

# Build settings
markdown: kramdown
kramdown:
  input: GFM
  hard_wrap: false

# Site Defaults
defaults:
  - scope:
      path: ""
    values:
      layout: "default"
